Repository marcomontalbano/figma-export, pull requests merged in 2022-09, with the labels that each got.

#132 Add 'filterComponent' option
  packages/core/src/lib/export-components.test.ts
  packages/core/src/lib/export-components.ts
  packages/core/src/lib/figma.ts
  packages/types/src/commands.ts
  packages/types/src/global.ts
Labels: PR: New Feature :rocket:

#133 Handle 'undefined' output from transformers
  packages/core/src/lib/figma.ts
  packages/core/src/lib/utils.ts
  packages/output-components-as-es6/src/index.test.ts
Labels: PR: Bug Fix :bug:

#134 Update dependencies to latest minor
  package.json
  packages/core/package.json
  packages/output-components-as-svgr/package.json
  packages/transform-svg-with-svgo/package.json
  packages/types/package.json
  packages/website/.eslintrc.js
  packages/website/package.json
  yarn.lock
Labels: PR: Dependencies :up:
