Repository marcomontalbano/figma-export, pull requests merged in 2024-02, with the labels that each got.

#155 Remove duplicate install pkg on README.md
  README.md
Labels: PR: Documentation :memo:

#159 Upgrade axios to the latest version
  package.json
  packages/core/package.json
  packages/types/package.json
  yarn.lock
Labels: PR: Dependencies :up:

#158 Filter for string urls only
  packages/core/src/lib/figma.ts
Labels: PR: Bug Fix :bug:

#160 Add `includeTypes` attribute to support component instance
  packages/cli/src/commands/components.ts
  packages/cli/src/utils.ts
  packages/core/src/integration.test.ts
  packages/core/src/lib/_config.test.ts
  packages/core/src/lib/export-components.ts
  packages/core/src/lib/figma.test.ts
  packages/core/src/lib/figma.ts
  packages/output-components-as-es6/src/index.test.ts
  packages/output-components-as-stdout/src/index.test.ts
  packages/output-components-as-svg/src/index.test.ts
  packages/output-components-as-svgr/src/index.test.ts
  packages/output-components-as-svgstore/src/index.test.ts
  packages/types/src/commands.ts
  packages/types/src/global.ts
Labels: PR: New Feature :rocket:

#157 Update all dependencies – drop support for Node.js 12 and 14
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .yarn/releases/yarn-3.1.1.cjs
  .yarn/releases/yarn-3.8.0.cjs
  .yarnrc.yml
  package.json
  packages/cli/package.json
  packages/core/package.json
  packages/output-components-as-es6/package.json
  packages/output-components-as-stdout/package.json
  packages/output-components-as-svg/package.json
  packages/output-components-as-svgr/README.md
  packages/output-components-as-svgr/package.json
  packages/output-components-as-svgstore/package.json
  packages/output-styles-as-css/package.json
  packages/output-styles-as-less/package.json
  packages/output-styles-as-sass/package.json
  packages/output-styles-as-style-dictionary/package.json
  packages/transform-svg-with-svgo/package.json
  packages/transform-svg-with-svgo/src/index.test.ts
  packages/transform-svg-with-svgo/src/index.ts
  packages/types/package.json
  packages/utils/package.json
  packages/website/.figmaexportrc.js
  packages/website/next.config.js
  packages/website/package.json
  yarn.lock
Labels: PR: Dependencies :up:, PR: Breaking Changes :comet:

#162 Add `overrides` for axios
  package.json
  packages/core/package.json
  packages/types/package.json
Labels: PR: Bug Fix :bug:
